#include "modules/register_module_types.h"

void initialize_dungeon_generator_module(ModuleInitializationLevel p_level);
void uninitialize_dungeon_generator_module(ModuleInitializationLevel p_level);
